name: Check Links

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: gaurav-nelson/github-action-markdown-link-check@1b916f2cf6c36510a6059943104e3c42ce6c16bc # 1.0.16
      with:
        use-quiet-mode: 'yes'
        config-file: '.github/workflows/mlc_config.json'
